steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app/gemini-notes-app:$COMMIT_SHA',
      '.'
    ]

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app/gemini-notes-app:$COMMIT_SHA'
    ]

# Step 3: Create a Cloud Deploy release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -x
      printenv PROJECT_ID
      sed -i 's#\$PROJECT_ID#'"$PROJECT_ID"'#g' clouddeploy.yaml
      sed -i 's#\$PROJECT_ID#'"$PROJECT_ID"'#g' skaffold.yaml
      gcloud deploy releases create rel-${SHORT_SHA} \
        --project=${PROJECT_ID} \
        --delivery-pipeline=gemini-notes-app-pipeline \
        --region=us-central1 \
        --skaffold-file=skaffold.yaml \
        --images=gemini-notes-app=us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app/gemini-notes-app:$COMMIT_SHA \
        --description="Cloud Build automated release"

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/notes-app/gemini-notes-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
