apiVersion: skaffold/v2
kind: Config
metadata:
  name: notes-app
build:
  artifacts:
  - image: gcr.io/${PROJECT_ID}/notes-app/gemini-notes-app # Using PROJECT_ID for project ID
    docker:
      dockerfile: Dockerfile
      context: .
deploy:
  cloudrun:
    projectid: ${PROJECT_ID}
    region: us-central1
    service: gemini-notes-app
    # If your Cloud Run service requires specific environment variables, memory,
    # CPU, or other configurations, they can be added here.
    # For example:
    # concurrency: 80
    # memory: 512Mi
    # env:
    # - name: MY_VARIABLE
    #   value: "my_value"
    